retrieved_metadata/package/objects/Wired_Mail_Sign_Up__c.object
<CustomObject>
    <fields>
        <fullName>Sign_Up_Date__c</fullName>
        <description>The date the User signed up for Wired Brain Mail.</description>
        <inlineHelpText>The date the User signed up for Wired Brain Mail.</inlineHelpText>
        <label>Sign Up Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Unsubscribe_Date__c</fullName>
        <description>If the User is no longer active, the date they unsubscribed to receive Wired Brain Mail.</description>
        <inlineHelpText>If the User is no longer active, the date they unsubscribed to receive Wired Brain Mail.</inlineHelpText>
        <label>Unsubscribe Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The User who signed up for Wired Brain Mail.</description>
        <inlineHelpText>The User who signed up for Wired Brain Mail.</inlineHelpText>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Wired_Mail_Sign_Ups</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Wired Mail Sign Up</label>
    <nameField>
        <displayFormat>WMSU-{00000}</displayFormat>
        <label>Wired Mail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wired Mail Sign Ups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/MailListViewController.cls
public with sharing class MailListViewController 
{    
    // Constructor with no implementation...
    public MailListViewController(){}

    @AuraEnabled
    public static string submitAction()
    {
        Id currentUserId = UserInfo.getUserId();
        
        if (hasExistingSignUp(currentUserId))
            return 'Sorry, your User is already signed up to Wired Brain Mail.';

        User currentUser = retrieveUser(currentUserId);
        signUp(currentUser);        
        String signedUpMessage = 'You\'re now signed up, ' + currentUser.FirstName + '!';
        return signedUpMessage;
    }

    @AuraEnabled
    public static string unsubscribe()
    {
        Id currentUserId = UserInfo.getUserId();
        if (hasExistingSignUp(currentUserId))
            return addUnsubcribeDate(currentUserId);

        return 'Could not locate an existing sign up to unsubscribe to. I think you\'re fine!';
    }

    public static string addUnsubcribeDate(Id userId)
    {
        System.debug('Unsubscribing User: ' + userId);
        Wired_Mail_Sign_Up__c currentUserSignup = [SELECT Id, 
                                                        User__c,
                                                        Sign_Up_Date__c, 
                                                        Unsubscribe_Date__c 
                                                    FROM Wired_Mail_Sign_Up__c
                                                    WHERE Sign_Up_Date__c != null
                                                        AND Unsubscribe_Date__c = null
                                                        AND User__c = :userId
                                                    LIMIT 1];

        update new Wired_Mail_Sign_Up__c(Id = currentUserSignup.Id, Unsubscribe_Date__c = Date.today());
        System.debug('User unsubscribed');
        return 'You\'re now unsubscribed. No more Wired Announcements for you!';        
    }

    public static Boolean hasExistingSignUp(Id userId)
    {
        List<Wired_Mail_Sign_Up__c> existingSignUps = [SELECT Id, User__c 
                                                        FROM Wired_Mail_Sign_Up__c 
                                                        WHERE User__c = :userId
                                                        AND Unsubscribe_Date__c = null];
        
        if (existingSignUps.size() > 0)
            return true;
        else
            return false;
    }
    
    public static User retrieveUser(Id userId)
    {
        User currentUser = [SELECT Id, FirstName, LastName, Email
                             FROM User WHERE Id = :userId];
        return currentUser;
    }

    public static Wired_Mail_Sign_Up__c signUp(User user)
    {        
        Wired_Mail_Sign_Up__c signup = new Wired_Mail_Sign_Up__c(
            User__c = user.Id,
            Sign_Up_Date__c = Date.today()
        );
        insert signup;
        System.enqueueJob(new WiredAnnouncementsSharing(new List<User>{user}));
        return signup;
    }
}